"""empty message

Revision ID: 2249e5c0348b
Revises: b87bdd4b080f
Create Date: 2020-12-13 18:40:28.774289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2249e5c0348b'
down_revision = 'b87bdd4b080f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_relationship', 'Related',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_relationship', 'Relating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_relationship', 'Relating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_relationship', 'Related',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
