"""empty message

Revision ID: 307d733d08e7
Revises: cc1d5575f134
Create Date: 2020-12-17 15:46:32.185638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307d733d08e7'
down_revision = 'cc1d5575f134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Relating', sa.Integer(), nullable=False),
    sa.Column('Related', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Integer(), nullable=False),
    sa.Column('Relating_name', sa.String(length=100), server_default='1', nullable=True),
    sa.Column('Related_name', sa.String(length=100), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_relationship'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relationship')
    # ### end Alembic commands ###
