"""empty message

Revision ID: 34b7720999b7
Revises: 69053cd831c1
Create Date: 2020-12-13 19:13:16.408196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b7720999b7'
down_revision = '69053cd831c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_relationship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_relationship', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['Relating'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['Related'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
