"""empty message

Revision ID: 69053cd831c1
Revises: 8d58d7d9348d
Create Date: 2020-12-13 18:43:01.180354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69053cd831c1'
down_revision = '8d58d7d9348d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_relationship', schema=None) as batch_op:
        batch_op.alter_column('Related',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Relating',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_relationship', schema=None) as batch_op:
        batch_op.alter_column('Relating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Related',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
