"""empty message

Revision ID: 8aca639e4a97
Revises: b118c4b9a16e
Create Date: 2020-12-13 19:15:21.303634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aca639e4a97'
down_revision = 'b118c4b9a16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_relationship', type_='foreignkey')
    op.drop_constraint(None, 'user_relationship', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_relationship', 'user', ['Related'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_relationship', 'user', ['Relating'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
