"""empty message

Revision ID: 908b7ddfd6d5
Revises: fb36d77cf245
Create Date: 2020-12-13 18:22:03.576162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908b7ddfd6d5'
down_revision = 'fb36d77cf245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_relationship', 'Related',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_relationship', 'Relating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user_relationship', 'user', ['Relating'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_relationship', 'user', ['Related'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_relationship', type_='foreignkey')
    op.drop_constraint(None, 'user_relationship', type_='foreignkey')
    op.alter_column('user_relationship', 'Relating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_relationship', 'Related',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
