"""empty message

Revision ID: d6f08a6ef454
Revises: 4426aa14fe06
Create Date: 2020-12-12 08:21:43.444920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f08a6ef454'
down_revision = '4426aa14fe06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Relating', sa.Integer(), nullable=False),
    sa.Column('Related', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_relationship')
    # ### end Alembic commands ###
